<?php

namespace Chm\MPFormBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotationRepository extends EntityRepository
{
}
